services:
  postgres:
    image: postgres:18
    container_name: lucario-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: lucario
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      TZ: Asia/Tokyo
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d lucario"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: lucario-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
  redis_data: