// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import {defineConfig, env} from "prisma/config";


const DATABASE_URL =
    `postgresql://` +
    `${env("DB_USER")}:` +
    `${env("DB_PASSWORD")}@` +
    `${env("DB_HOST")}:` +
    `${env("DB_PORT")}/` +
    `${env("DB_NAME")}`;

export default defineConfig({
    schema: "prisma/schema.prisma",
    migrations: {
        path: "prisma/migrations",
    },
    datasource: {
        url: DATABASE_URL,
    },
});
